apiVersion: 1.0.0
metadata:
  generateName: golang-
projects:
  - name: example
    source:
      type: git
      location: '<repourl>'
    clonePath: /projects/work/
components:
  - type: dockerimage
    image: 'docker.io/kazimsarikaya/che-golang-1.16:latest'
    alias: go-cli
    env:
      - name: USER
        value: ""
      - name: PROJECT
        value: ""
      - name: REPOHOST
        value: ""
    endpoints:
      - name: 8080-tcp
        port: 8080
    memoryLimit: 2Gi
    mountSources: true
commands:
  - name: 1.1 Build
    actions:
      - type: exec
        workdir: /projects/work/
        component: go-cli
        command: make build
  - name: 1.2 Build Tests
    actions:
      - type: exec
        workdir: /projects/work/
        component: go-cli
        command: make build test
  - name: 1.3 Run Tests
    actions:
      - type: exec
        workdir: /projects/work/
        component: go-cli
        command: make build test run
  - name: 2.1 Init Project
    actions:
      - type: exec
        workdir: /projects/work/
        component: go-cli
        command: make project init
  - name: 2.2 Destroy Project
    actions:
      - type: exec
        workdir: /projects/work/
        component: go-cli
        command: make project destroy
